baseURL = "https://blog.nasustim.com/"
languageCode = "ja-jp"
title = "nasustim's weblog"
theme = "paper"
contentDir = "articles/"

googleAnalytics = 'G-3YY246MS11'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# for theme
# see: https://github.com/nanxiaobei/hugo-paper/tree/main#options
[params]
twitter = "nasustim"
github = "nasustim"

disableHLJS = false
monoDarkIcon = true
