name: Test Renovate

on:
  push:
    paths:
      - renovate.json
      - .github/workflows/test_renovate.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@v4

      - name: Test Renovate
        run: npx --package renovate -c 'renovate-config-validator'
