name: Test Renovate

on:
  push:
    paths:
      - renovate.json
      - .github/workflows/test_renovate.yml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3

      - name: Test Renovate
        run: npx --package renovate -c 'renovate-config-validator'
